repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: check-toml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [--exclude, tests]
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.1.3
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
      - id: xenon
        args: ["--max-average=A", "--max-modules=B", "--max-absolute=B"]
  - repo: local
    hooks:
      - id: pylint
        entry: pylint
        language: system
        name: pylint
        types: [python]
