[tool.black]
line-length = 100
skip-string-normalization = true

[tool.pylint.messages_control]
# C0103 - invalid-name
# C0330 - bad-continuation
# R0801 - duplicate-code
# R0903 - too-few-public-methods
# R0913 - too-many-arguments
# W0511 - fixme
# W1203 - logging-fstring-interpolation
disable = "C0103,C0330,R0801,R0903,R0913,W0511,W1203"
